# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Algorithm Visualizer CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set env variables in .env
        run: echo "PORT=${{secrets.PORT}}" >> .env

      - name: Run the app
        run: npm i
      - run: npm run build --if-present

      # Check if pm2 process with name 'algorithm-visualizer' exists
      - name: Check if pm2 process exists
        id: pm2_check
        run: pm2 list | grep -q "algorithm-visualizer" || echo "::set-output name=exists::false"

      # Start pm2 process if it doesn't exist
      - name: Start pm2 process
        if: steps.pm2_check.outputs.exists == 'false'
        run: pm2 start algorithm-visualizer

      # Restart pm2 process
      - name: Restart pm2 process
        run: pm2 restart algorithm-visualizer
